#/config/initializers/aws.yml

defaults: &defaults
  #https://console.aws.amazon.com/iam/home?#users -> Security Credentials (S3_user_policy.json)
  access_key_id: 'AKIAJKB4CHFSC5MFC6EQ'
  secret_access_key: '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'
  #necessary if the bucket is outside US: http://docs.aws.amazon.com/general/latest/gr/rande.html
  region: 'us-east-1'
production:
  <<: *defaults
  bucket: 'jpcomp'